minino/minino/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('purchaser/', include('purchaser.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

minino/purchaser/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.purchaser_home, name='purchaser_home'),
    path('create_purchaser/', views.create_purches, name='create_purchaser'),
    path('signin/', views.signin, name='signin'),
    path('admin_home/', views.admin_home, name='admin_home'),
    path('all_purchases/', views.all_purchases, name='all_purchases'),
    path('search_by_user/', views.search_by_user, name='search_by_user'),
    path('purchases_by_user/<int:purchaser_id>/', views.purchases_by_user, name='purchases_by_user'),
    path('search_by_state/', views.search_by_state, name='search_by_state'),
]

minino/catalog/models.py
from django.db import models
from purchaser.models import PurchaserModel
from datetime import datetime

class StoreModel(models.Model):
    store_name = models.CharField(max_length=50)
    phone = models.PositiveIntegerField()

    def __str__(self):
        return self.store_name

class ProviderModel(models.Model):
    provider_name = models.CharField(max_length=50)
    phone = models.PositiveIntegerField()
    address = models.CharField(max_length=50)

    def __str__(self):
        return self.provider_name

class CategoryModel(models.Model):
    category_name = models.CharField(max_length=50)
    store = models.ForeignKey(StoreModel, on_delete=models.CASCADE)

    def __str__(self):
        return self.category_name

class ProductModel(models.Model):
    product_name = models.CharField(max_length=50)
    categories = models.ManyToManyField(CategoryModel)
    price_purchase = models.PositiveIntegerField()
    price_sale = models.PositiveIntegerField()
    providers = models.ManyToManyField(ProviderModel)
    product_img = models.ImageField(upload_to='products_img0/', null=True, blank=True)

    def __str__(self):
        return self.product_name

class CartModel(models.Model):
    STATE_CHOICES = (
        ('in_process', 'In Process'),
        ('pending', 'Pending'),
        ('paid', 'Paid'),
    )

    purchaser = models.ForeignKey(PurchaserModel, on_delete=models.CASCADE)
    products = models.ManyToManyField(ProductModel)
    total_price = models.PositiveIntegerField()
    state = models.CharField(max_length=20, choices=STATE_CHOICES)
    purchase_datetime = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return f'Cart #{self.id}'
    
class ProductInCart(models.Model):
    product = models.ForeignKey(ProductModel, on_delete=models.CASCADE)
    cart = models.ForeignKey(CartModel, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    partial_price = models.PositiveIntegerField()

minino/purchaser/models.py
from django.db import models

# Create your models here.
class PurchaserModel(models.Model):
    name = models.CharField(max_length=50)
    phone = models.PositiveIntegerField()

minino/purchaser/views.py
from django.shortcuts import render, redirect
from .models import PurchaserModel

# Create your views here.
def purchaser_home(request):
    return render(request, 'purchaser_home.html')

def create_purches(request):
    if request.method == 'POST':
        purchaser_name = request.POST.get('purchaser_name')
        phone = request.POST.get('purchaser_phone') 
        new_purchaser = PurchaserModel(name=purchaser_name, phone=phone)
        new_purchaser.save()
        message = 'Purchaser created successfully'
        return render(request, 'create_purchaser.html', {'message': message})
    return render(request, 'create_purchaser.html')

def signin(request):
    purchasers = [] 
    
    if request.method == 'POST':
        search_query = request.POST.get('search_purchase')
        
        if search_query:
            purchasers = PurchaserModel.objects.filter(name__icontains=search_query)
    
    return render(request, 'signin.html', {'purchasers': purchasers})

from django.shortcuts import render
from catalog.models import CartModel, ProductInCart


def admin_home(request):


    return render(request, 'admin_home.html')

def all_purchases(request):
    # Recupera todas las compras (carritos) de la base de datos
    all_carts = CartModel.objects.all()

    # Puedes realizar cualquier procesamiento adicional aquí si es necesario

    return render(request, 'all_purchases.html', {'all_carts': all_carts})

def search_by_user(request):
    purchasers = [] 
    
    if request.method == 'POST':
        search_query = request.POST.get('search_purchase')
        
        if search_query:
            purchasers = PurchaserModel.objects.filter(name__icontains=search_query)
    return render(request, 'search_by_user.html', {'purchasers':purchasers})

def purchases_by_user(request, purchaser_id):
    purchaser = PurchaserModel.objects.get(pk=purchaser_id)
    carts_by_purchaser = CartModel.objects.filter(purchaser=purchaser)
    
    if request.method == 'POST':
        for cart in carts_by_purchaser:
            new_state = request.POST.get(f'new_state_{cart.id}')  # Captura el nuevo estado del carrito específico
            if new_state:
                cart.state = new_state
                cart.save()

    return render(request, 'purchases_by_user.html', {'carts_by_purchaser': carts_by_purchaser, 'purchaser': purchaser})

def search_by_state(request):
    if request.method == 'POST':
        selected_state = request.POST.get('state')  # Obtener el valor del campo 'state' del formulario
        carts_in_state = CartModel.objects.filter(state=selected_state)
        # Ahora puedes hacer lo que necesites con el valor 'selected_state'
        return render(request, 'search_by_state.html', {'carts_in_state': carts_in_state})
    return render(request, 'search_by_state.html')

minino/purchaser/templates/admin_home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Home</title>
</head>
<body>
    <h1>Admin Home</h1>
    <a href="{% url 'purchaser_home' %}">Purchaser home</a>
    <a href="{% url 'all_purchases' %}">Todas las compras</a>
    <a href="{% url 'search_by_user' %}">Buscar por usuario</a>
    <a href="{% url 'search_by_state' %}">Buscar por estado</a>
    <a href="{% url 'admin_stores' %}">Admin stores</a>
</body>
</html>

minino/purchaser/templates/all_purchases.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>All Purchases</title>
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }

        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>
    <h1>Todas las Compras</h1>
    <table>
        <thead>
            <tr>
                <th>ID de Compra</th>
                <th>Comprador</th>
                <th>Total</th>
                <th>Estado</th>
                <th>Fecha de Compra</th> <!-- Nueva columna para mostrar la fecha -->
                <th>Productos</th>
            </tr>
        </thead>
        <tbody>
            {% for cart in all_carts %}
            <tr>
                <td>{{ cart.id }}</td>
                <td>{{ cart.purchaser.name }}</td>
                <td>{{ cart.total_price }}</td>
                <td>{{ cart.state }}</td>
                <td>{{ cart.purchase_datetime|date:"Y-m-d H:i:s" }}</td> <!-- Muestra la fecha formateada -->
                <td>
                    <ul>
                        {% for product_in_cart in cart.productincart_set.all %}
                        <li>{{ product_in_cart.product.product_name }} (Cantidad: {{ product_in_cart.quantity }})</li>
                        {% endfor %}
                    </ul>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <div>
        <a href="{% url 'admin_home' %}">Admin Home</a>
    </div>
</body>
</html>

minino/purchaser/templates/create_purchaser.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Purchaser</title>
</head>
<body>
    <h1>Crear comprador</h1>
    <a href="{% url 'purchaser_home' %}">Regresar a home</a>
    <p>{{ message }}</p>
    <form method='POST'>
        {% csrf_token %}
        <label for="purchaser_name">Nombre del cliente</label>
        <input type="text" name="purchaser_name" id="purchaser_name">
        <label for="purchaser_phone">Telefono del cliente</label>
        <input type="number" name="purchaser_phone" id="purchaser_phone">
        <button type="submit">Crear</button>
    </form>
</body>
</html>

minino/purchaser/templates/purchaser_home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Purchaser Home</title>
</head>
<body>
    <div>
        <h1>Purchaser Home</h1>
    </div>
    <div>
        <a href="{% url 'create_purchaser' %}">Crear cliente</a>
        <a href="{% url 'signin' %}">Login</a>
        <a href="{% url 'admin_home' %}">Admin_home</a>
    </div>
</body>
</html>

minino/purchaser/templates/purchases_by_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Purchases by User</title>
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }

        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>
    <h1>Purchases by User: {{ purchaser.name }}</h1>

    <table>
        <thead>
            <tr>
                <th>ID de Compra</th>
                <th>Total</th>
                <th>Estado</th>
                <th>Fecha de Compra</th>
                <th>Productos</th>
                <th>Precio Unitario</th>
                <th>Cambiar Estado</th> <!-- Nueva columna para el select -->
            </tr>
        </thead>
        <tbody>
            {% for cart in carts_by_purchaser %}
            <tr>
                <td>{{ cart.id }}</td>
                <td>{{ cart.total_price }}</td>
                <td>{{ cart.state }}</td>
                <td>{{ cart.purchase_datetime|date:"Y-m-d H:i:s" }}</td>
                <td>
                    <ul>
                        {% for product_in_cart in cart.productincart_set.all %}
                        <li>{{ product_in_cart.product.product_name }} (Cantidad: {{ product_in_cart.quantity }})</li>
                        {% endfor %}
                    </ul>
                </td>
                <td>
                    <ul>
                        {% for product_in_cart in cart.productincart_set.all %}
                        <li>${{ product_in_cart.product.price_sale }}</li>
                        {% endfor %}
                    </ul>
                </td>
                <td>
                    <form method="POST">
                        {% csrf_token %}
                        <select name="new_state_{{ cart.id }}">
                            <option value="in_process" {% if cart.state == 'in_process' %}selected{% endif %}>In Process</option>
                            <option value="pending" {% if cart.state == 'pending' %}selected{% endif %}>Pending</option>
                            <option value="paid" {% if cart.state == 'paid' %}selected{% endif %}>Paid</option>
                        </select>
                        <button type="submit" name="update_cart_{{ cart.id }}">Guardar</button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <div>
        <a href="{% url 'admin_home' %}">Admin Home</a>
    </div>

    {% if carts_by_purchaser|length == 0 %}
    <p>No purchases found for this user.</p>
    {% endif %}
</body>
</html>

minino/purchaser/templates/search_by_state.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Search By State</title>
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }

        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
            cursor: pointer; /* Cambiar el cursor al pasar por encima para indicar que se puede ordenar */
        }

        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>
    <h1>Search by state</h1>
    <form method="POST">
        {% csrf_token %}
        <label for="state">Selecciona un estado:</label>
        <select name="state" id="state">
            <option value="in_process">In Process</option>
            <option value="pending">Pending</option>
            <option value="paid">Paid</option>
        </select>
        <button type="submit">Buscar</button>
    </form>

    <!-- Agrega una tabla en cuadrícula para mostrar los carros -->
    <h2>Carros en el estado seleccionado:</h2>
    <table>
        <thead>
            <tr>
                <th onclick="sortTable(0)">ID de Compra</th>
                <th onclick="sortTable(1)">Comprador</th>
                <th onclick="sortTable(2)">Total</th>
                <th onclick="sortTable(3)">Estado</th>
                <th onclick="sortTable(4)">Fecha de Compra</th>
                <!-- Puedes agregar más columnas aquí según tus necesidades -->
            </tr>
        </thead>
        <tbody>
            {% for cart in carts_in_state %}
                <tr>
                    <td>{{ cart.id }}</td>
                    <td>{{ cart.purchaser.name }}</td>
                    <td>{{ cart.total_price }}</td>
                    <td>{{ cart.state }}</td>
                    <td>{{ cart.purchase_datetime|date:"Y-m-d H:i:s" }}</td>
                    <!-- Puedes agregar más columnas aquí según tus necesidades -->
                </tr>
            {% empty %}
                <tr>
                    <td colspan="5">No se encontraron carros en este estado.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <div>
        <a href="{% url 'admin_home' %}">Admin Home</a>
    </div>

    <script>
        // Función para ordenar la tabla por la columna especificada
        function sortTable(columnIndex) {
            const table = document.querySelector('table');
            const rows = Array.from(table.querySelectorAll('tr'));

            // Remover la fila de encabezado
            const headerRow = rows.shift();

            // Ordenar las filas según el contenido de la columna seleccionada
            rows.sort((a, b) => {
                const aValue = a.cells[columnIndex].textContent.trim();
                const bValue = b.cells[columnIndex].textContent.trim();
                return aValue.localeCompare(bValue, undefined, { numeric: true, sensitivity: 'base' });
            });

            // Agregar las filas nuevamente a la tabla
            rows.unshift(headerRow); // Agregar la fila de encabezado nuevamente
            table.tBodies[0].innerHTML = rows.map(row => row.outerHTML).join('');
        }
    </script>
</body>
</html>

minino/purchaser/templates/search_by_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Search by User</title>
</head>
<body>
    <h1>Search by User</h1>
    <form method="post">
        {% csrf_token %}
        <label for="search_purchase">Enter User Name:</label>
        <input type="text" id="search_purchase" name="search_purchase">
        <button type="submit">Search</button>
    </form>

    {% if purchasers %}
    <h2>Search Results:</h2>
    <ul>
        {% for purchaser in purchasers %}
        <a href="{% url 'purchases_by_user' purchaser.id %}">{{ purchaser.name }}</a>
        {% endfor %}
    </ul>
    {% else %}
    <p>No results found.</p>
    {% endif %}
</body>
</html>

minino/purchaser/templates/signin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Signin</title>
</head>
<body>
    <h1>Signin</h1>
    <form method="POST">
        {% csrf_token %}
        <input type="text" name="search_purchase" id="search_purchase">
        <label for="search_purchase">Buscar comprador</label>
        <button type="submit">Buscar</button>
    </form>
    {% if purchasers %}
    <h2>Resultados de la búsqueda:</h2>
    <ul>
        {% for purchaser in purchasers %}
        <a href="{% url 'catalog_home' purchaser.id %}">{{ purchaser.name }}</a>
    
        {% endfor %}
    </ul>
    {% else %}
        <p>No se encontraron compradores</p>
    {% endif %}
    
    
</body>
</html>